import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";

export default function Chat() {
  const [messages, setMessages] = useState([]);
  const [uploadedFiles, setUploadedFiles] = useState([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [selectedModel, setSelectedModel] = useState("/predict/adaboost");
  const [user, setUser] = useState(null);

  const inputRef = useRef();
  const chatContainerRef = useRef();
  const navigate = useNavigate();
  const API_BASE = "http://localhost:5050";

  useEffect(() => {
    const userData = localStorage.getItem("user");
    if (userData) {
      setUser(JSON.parse(userData));
    }
    newChat();
  }, []);

  function newChat() {
    setMessages([
      {
        role: "assistant",
        content:
          "Hello! Upload your code or paste a snippet and I'll analyze whether it's machine-generated or human-written.",
      },
    ]);
    setUploadedFiles([]);
    setIsAnalyzing(false);
  }

  function scrollToBottom() {
    setTimeout(() => {
      if (chatContainerRef.current) {
        chatContainerRef.current.scrollTop =
          chatContainerRef.current.scrollHeight;
      }
    }, 100);
  }

  function addMessage(msg) {
    setMessages((prev) => [...prev, msg]);
    scrollToBottom();
  }

  function handleFileUpload(e) {
    const files = Array.from(e.target.files);
    const allowed = [
      "js", "jsx", "ts", "tsx", "py", "java", "cpp", "c", "cs",
      "go", "rs", "rb", "php", "swift", "kt"
    ];

    files.forEach((file) => {
      const ext = file.name.split(".").pop().toLowerCase();
      if (!allowed.includes(ext)) return;

      const reader = new FileReader();
      reader.onload = (ev) => {
        setUploadedFiles((prev) => [
          ...prev,
          {
            name: file.name,
            size: file.size,
            content: ev.target.result,
          },
        ]);
      };
      reader.readAsText(file);
    });

    e.target.value = "";
  }

  function removeFile(index) {
    setUploadedFiles((prev) => prev.filter((_, i) => i !== index));
  }

  async function analyzeWithEndpoint(text, files) {
  const form = new FormData();

  if (text.trim().length > 0) {
    const blob = new Blob([text], { type: "text/plain" });
    form.append("file", blob, "input.txt");
  }

  files.forEach((f) => {
    const blob = new Blob([f.content], { type: "text/plain" });
    form.append("file", blob, f.name);
  });

  const res = await fetch(`${API_BASE}${selectedModel}`, {
    method: "POST",
    body: form,
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    console.error("Backend error", res.status, text);
    return { error: `Server error (${res.status})` };
  }

  return await res.json();
}

  

  async function handleSubmit(e) {
    e.preventDefault();
    if (isAnalyzing) return;

    const text = inputRef.current.value.trim();
    const hasFiles = uploadedFiles.length > 0;

    if (!text && !hasFiles) return;

    addMessage({
      role: "user",
      content: text || `Uploaded ${uploadedFiles.length} file(s)`,
      files: hasFiles ? uploadedFiles : null,
    });

    setIsAnalyzing(true);
    inputRef.current.value = "";

    addMessage({ role: "assistant", content: "Analyzing…" });

    const result = await analyzeWithEndpoint(text, uploadedFiles);

    setMessages((prev) => prev.slice(0, -1));
    setUploadedFiles([]);

    if (result.error) {
      addMessage({
        role: "assistant",
        content: `❌ Error: ${result.error}`,
      });
      setIsAnalyzing(false);
      return;
    }

    addMessage({
      role: "assistant",
      content: `Model ${result.model} analyzed your code.\n\nCode generated by: ${result.label}**`,
      analysis: result,
    });


    setIsAnalyzing(false);
  }

  const handleLogout = () => {
    localStorage.removeItem("session_token");
    localStorage.removeItem("user");
    navigate("/");
  };

  return (
    <div className="app">
      <header className="header">
        <div className="header-content">
          <div className="header-left">
            <div className="logo">⚡</div>
            <div className="header-text">
              <h1>SemEval 2026 Task 13</h1>
              <p>Detecting Machine-Generated Code</p>
            </div>
          </div>
          <div className="header-actions">
            {user && (
              <div className="user-menu">
                <span className="user-name">{user.email}</span>
                <button className="btn btn-outline" onClick={() => navigate("/subscriptions")}>
                  Subscriptions
                </button>
                <button className="btn btn-outline" onClick={handleLogout}>
                  Logout
                </button>
              </div>
            )}
            <button className="btn btn-outline" onClick={newChat}>New Chat</button>
          </div>
        </div>
      </header>

      <div className="chat-container" ref={chatContainerRef}>
        <div className="messages">
          {messages.map((m, i) => (
            <Message key={i} {...m} />
          ))}
        </div>
      </div>

      {/* INPUT */}
      <div className="input-area">
        <div className="input-content">
          <div className="model-select">
            <label>Model:</label>
            <select
              value={selectedModel}
              onChange={(e) => setSelectedModel(e.target.value)}
            >
              <option value="/predict/adaboost">AdaBoost</option>
              <option value="/predict/svm">SVM</option>
              <option value="/predict/lstm">LSTM</option>
              <option value="/predict/transformer">Transformer</option>
            </select>
          </div>

          <div className="uploaded-files">
            {uploadedFiles.map((f, i) => (
              <div className="file-chip" key={i}>
                <span>{f.name}</span>
                <button onClick={() => removeFile(i)}>✖</button>
              </div>
            ))}
          </div>

          <form className="input-form" onSubmit={handleSubmit}>
            <textarea
              ref={inputRef}
              className="message-input"
              placeholder="Paste your code or upload files…"
              rows={3}
            ></textarea>

            <div className="input-actions">
              <input
                type="file"
                id="fileInput"
                multiple
                style={{ display: "none" }}
                onChange={handleFileUpload}
              />
              <button
                type="button"
                className="btn btn-icon"
                onClick={() => document.getElementById("fileInput").click()}
              >
                📎
              </button>
              <button type="submit" className="btn btn-primary">➤</button>
            </div>
          </form>

          <p className="input-hint">
            Press Enter to send — Shift+Enter for new line
          </p>
        </div>
      </div>
    </div>
  );
}

/************************************
 * MESSAGE COMPONENT
 ************************************/
function Message({ role, content, files, analysis }) {
  return (
    <div className={`message ${role}`}>
      {role === "assistant" && <Avatar role={role} />}

      <div className="message-content">
        {files &&
          files.map((f, i) => (
            <div className="file-card" key={i}>
              <div className="file-info">
                <div className="file-name">{f.name}</div>
                <div className="file-size">{(f.size / 1024).toFixed(1)} KB</div>
                <pre className="file-preview">
                  {f.content.slice(0, 300)}
                  {f.content.length > 300 ? "..." : ""}
                </pre>
              </div>
            </div>
          ))}

        <div className="message-bubble">
          <div className="message-text">{content}</div>
        </div>

        {analysis && (
          <div className="analysis-card">
            {/* <div
              className={`analysis-icon ${
                analysis.label === "machine" ? "machine" : "human"
              }`}
            >
              ●
            </div> */}

            <div className="analysis-content">
              <div className="analysis-header">
                <span className="analysis-label">
                  Prediction:{" "}
                  <span
                    className={`analysis-prediction ${analysis.label}`}
                  >
                    {analysis.label === "machine"
                      ? "Machine-Generated"
                      : "Human-Written"}
                  </span>, Probability {analysis.probability_machine} (&gt;0.5 to be Machine-Generated)
                </span>
              </div>

              {/* <div className="progress-bar">
                <div
                  className={`progress-fill ${analysis.label}`}
                  style={{ width: `${analysis.probability_machine}%` }}
                ></div>
              </div> */}
            </div>
          </div>
        )}
      </div>

      {role === "user" && <Avatar role={role} />}
    </div>
  );
}

function Avatar({ role }) {
  return (
    <div className={`message-avatar ${role}`}>
      {role === "assistant" ? "🤖" : "U"}
    </div>
  );
}
